[[constraint]]
  name = "github.com/Azure/draft"
  revision = "d9cab2fb284962f36bf11c363421d3670c49b7ed"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
