[[constraint]]
  name = "github.com/Azure/draft"
  revision = "a7347c56384cac96dca75daff75583b43968b7da"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
