name: "pack-repo"
version: "0.4.0"
usage: "The Draft pack repository plugin"
description: "The Draft pack repository plugin"
command: "$DRAFT_PLUGIN_DIR/bin/pack-repo"
hooks:
  bash:
    install: "$DRAFT_PLUGIN_DIR/scripts/get.sh"
  powershell:
    install: "powershell.exe $env:DRAFT_PLUGIN_DIR\\scripts\\get.ps1"
